### ISSUE TITLE
Project Mgmt > Projects > Details 메뉴의 'ProjectDetail' text 변경

### ISSUE THREAD

**Issue by hky0715** [cnpst/zcp-admin-project#19]
![image](https://user-images.githubusercontent.com/44337259/83854496-c22add00-a751-11ea-8045-b041c43b92c4.png)
**Project Mgmt > Projects > Detail 메뉴의 'ProjectDetail'**

![image](https://user-images.githubusercontent.com/44337259/83854772-277ece00-a752-11ea-9e7c-c3a5683bb041.png)
**Cluster Mgmt > Clusters > Detail 메뉴의 'ClusterDetail'**

Project Detail, Cluster Detail 로 space를 넣어주세요.

**Comment by kbtapjm** [comment]
수정 완료
