### ISSUE TITLE
Stakeholder 추가 시, 사용자 데이터 잔류 현상

### ISSUE THREAD

**Issue by hky0715** [cnpst/zcp-admin-project#2]
Stakeholder로 A 사용자를 입력 후,
A 사용자의 정보를 변경했음(이름을 A->B로 변경)

새로 B 사용자를 Stakeholder로 등록 시,
A 사용자의 정보가 자동으로 매핑되는 현상을 발견함
![image](https://user-images.githubusercontent.com/44337259/74006459-0f26be80-49bf-11ea-86e2-6ebfb19c4b1f.png)

**Comment by kbtapjm** [comment]
stakeholder 등록시에 Registration type 추가
- 신규 : 새로운 사용자 등록
- 기존 : 사용자 검색을 통해서 선택 후 등록 (사용자 정보 수정은 불가)

stakeholder 수정시
- 기존 등록된 사용자를 새롭게 등록 할수 도 있고,  사용자 검색을 통해서 선택 후 변경도 가능
- 사용자 정보 수정도 가능 (다만 사용자 정보 수정시에는 프로젝트에 등록된 사용자 정보가 일괄수정됨)
