### ISSUE TITLE
Project Mgmt > Projects > Detail 화면의 탭 위치 변경 요청

### ISSUE THREAD

**Issue by hky0715** [cnpst/zcp-admin-project#20]
![image](https://user-images.githubusercontent.com/44337259/83855288-d15e5a80-a752-11ea-9af4-9cd84c9e777e.png)

프로젝트 상세 화면의 'Contract' 탭을 'Sizing' 탭 옆으로 변경해주세요.

**Comment by kbtapjm** [comment]
수정 완료
