### ISSUE TITLE
Clusters 메뉴에서 product 추가 시 기존 이력 생성일자가 자동으로 변경됨

### ISSUE THREAD

**Issue by hky0715** [cnpst/zcp-admin-project#3]
아래와 같이 기존재하는 cloudzcp-lawai-prod cluster 내 prod env에 ZCP product를 추가함.
![image](https://user-images.githubusercontent.com/44337259/74012773-62543d80-49ce-11ea-854f-0697e20852c8.png)

product에 이미 등록되어있던 zdb의 created date는 2020-02-05일이었으나,
zcp를 추가하면서 zdb의 created date까지 2020-02-07로 재설정됨.

**Comment by kbtapjm** [comment]
Cluster Product는 개별적으로 처리되는것이 아니어서 클러스터 등록일로 변경 처리함
